import random
import string 

password_len = int(input ("Enter the length of password :"))
char_value  = string.ascii_letters + string.digits + string.punctuation
 
# password = ""

# for i in range(password_len):
#     password+=random.choice(char_value)


password = "".join([random.choice(char_value) for i in range(password_len)])

print("your password generated by computer is :",password)   
                                                                        

